kind: pipeline
name: default

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    when:
      event: [push, pull_request]
      branch: master
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./node_modules

  - name: install
    image: node:12
    when:
      event: [push, pull_request]
      branch: master
    commands:
      - yarn

  - name: lint-check (eslint)
    image: node:12
    group: checks
    when:
      event: [push, pull_request]
      branch: master
      status: success
    commands:
      - yarn lint-check

  - name: format-check (prettier)
    image: node:12
    group: checks
    when:
      event: [push, pull_request]
      branch: master
      status: success
    commands:
      - yarn format-check

  - name: chromatic (UI diff)
    image: node:12
    group: checks
    secrets: [chromatic_app_code]
    environment:
      CHROMATIC_APP_CODE:
        from_secret: chromatic_app_code
    when:
      event: [push, pull_request]
      branch: master
      status: success
    commands:
      - yarn chromatic

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    when:
      event: [push, pull_request]
      branch: master
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./node_modules

  - name: deploy
    image: appleboy/drone-ssh
    secrets: [ssh_key]
    when:
      event: push
      branch: master
      status: success
    settings:
      host: nansen.online.ntnu.no
      port: 22
      key:
        from_secret: ssh_key
      command_timeout: 4m
      script:
        - /srv/www/design-system/deploy.sh

volumes:
  - name: cache
    host:
      path: /tmp/cache
